# Generated by Django 5.1.4 on 2025-01-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_comment_commentor_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
